name = "camthink-site"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

[env.production]
name = "camthink-site"

[env.preview]
name = "camthink-site-preview"

